- name: Install and manage Apache on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
