---
- name: Install and manage Apache on Ubuntu
  hosts: all
  become: yes  # Run the playbook with sudo privileges
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is started and enabled
      service:
        name: apache2
        state: started
        enabled: yes
